Feature/feedback fix
italia/design-comuni-drupal-theme pull request #1
Opened 2022-09-06 07:44 UTC by ldm-acn

the feedback form should have a branching logic (different sets of answers) according to the chosen rating

2022-09-07 14:27 UTC, zetareticoli requested changes

2022-09-07 14:27 UTC, zetareticoli commented on comuni_theme/templates/block/block--valutazione.html.twig
> +                <h2 class="title-medium-2-semi-bold mb-0">Le informazioni sulla pagina sono chiare?</h2>
Modificare con "Quanto sono chiare le informazioni su questa pagina?"

2022-09-07 15:48 UTC, ldm-acn commented on comuni_theme/templates/block/block--valutazione.html.twig
> +                <h2 class="title-medium-2-semi-bold mb-0">Le informazioni sulla pagina sono chiare?</h2>
il testo e' stato modificato

2022-09-13 09:38 UTC, astagi approved these changes

2022-09-13 09:42 UTC, merged