feat: add href attribute for links in paragraph ricerca
italia/design-comuni-drupal-theme pull request #40
Opened 2022-11-30 12:08 UTC by ldm-acn

solves missing href in pragraph ricerca (issue [#24 )](https://github.com/italia/design-comuni-drupal-theme/issues/24)

2022-12-02 08:34 UTC, astagi requested changes

2022-12-02 08:34 UTC, astagi commented on comuni_theme/templates/field/field--paragraph--field-links--ricerca.html.twig
> +      <a class="list-item">
@ldm-acn qui è rimasto un tag <a> appeso, si può rimuovere?

2022-12-02 09:02 UTC, ldm-acn commented on comuni_theme/templates/field/field--paragraph--field-links--ricerca.html.twig
> +      <a class="list-item">
il tag e' stato rimosso

2022-12-05 15:29 UTC, merged

2022-12-05 15:29 UTC, astagi commented
Grazie @ldm-acn