feat: the news page should also show the fields documenti and datasets
italia/design-comuni-drupal-theme pull request #41
Opened 2022-11-30 15:30 UTC by ldm-acn

news details show fields documenti and datasets (solves [#18 ](https://github.com/italia/design-comuni-drupal-theme/issues/18))

2022-12-02 08:29 UTC, zetareticoli requested changes

2022-12-02 08:29 UTC, zetareticoli commented on comuni_theme/templates/node/node--notizia.html.twig
> +          <h4>Allegati</h4>
Il tag deve essere `<h2 class="mb-3">`

2022-12-02 08:29 UTC, zetareticoli commented on comuni_theme/templates/node/node--notizia.html.twig
> +          <h4>Dataset</h4>
Il tag deve essere `<h2 class="mb-3">`

2022-12-02 08:29 UTC, zetareticoli commented on comuni_theme/templates/node/node--notizia.html.twig
>            <h4>Documenti</h4>
Il tag deve essere `<h2 class="mb-3">`

2022-12-05 23:34 UTC, astagi commented
@ldm-acn appena sistemate le modifiche richieste da @zetareticoli procedo al merge :) grazie

2023-01-18 13:25 UTC, zetareticoli commented
@ldm-acn è possibile procedere con le correzioni, così chiudiamo PR e issue collegata? Grazie

2023-01-23 09:44 UTC, merged